spring:
  application:
    name: abonados
server:
  port: 0
  
eureka: 
 client:
   enabled: true
   register-with-eureka: true
   serviceUrl:
    defaultZone: http://localhost:8761/eureka
 instance:
  instance-id: ${spring.application.name}:${random.int}
logging:
  level:
    com:
      netflix:
        eureka: ON
        discovery: ON
management:
  endpoint:
    hystrix:
      stream:
        enabled: true
  endpoints:
    web:
      exposure:
        include: hystrix.stream
